In [1]:
import numpy as np

# 라이브러리를 사용하지 않고 직접 구현한 함수 사용
from layer import Sigmoid, Affine
from net import TwoLayerNet

### Layer `Sigmoid`

In [2]:
sigmoid_layer = Sigmoid()
sigmoid_layer.forward(0)

0.5

### Layer `Affine`

In [3]:
W = np.random.randn(2, 4)
b = np.random.randn(1, 4)

affine_layer = Affine(W, b)

In [4]:
x = np.array([10, 20])

In [5]:
affine_layer.forward(x)

array([[ 22.98263583,  15.93770336,  26.11625941, -19.11554269]])

### Net `TwoLayerNet`

In [6]:
input_size = 2
hidden_size = 4
output_size = 3

model = TwoLayerNet(input_size, hidden_size, output_size)
model

In [7]:
model.params

[array([[ 0.28194247,  0.84989117,  0.77087025,  0.4546018 ],
        [ 1.47070206,  0.51816474, -0.23874363, -1.7211481 ]]),
 array([-1.1312036 , -0.69302441,  1.4411671 ,  0.83407358]),
 array([[ 0.50586844, -0.12473781, -0.41231459],
        [ 0.23422766,  0.56194801, -1.02909731],
        [-2.14129448,  0.00906642,  0.31027592],
        [-1.08932689,  0.36296808, -0.03300247]]),
 array([1.83343884, 1.38541034, 1.76140123])]

In [8]:
model.predict(x)

array([0.45886035, 1.83157425, 0.62640801])