In [1]:
import numpy as np

# 라이브러리를 사용하지 않고 직접 구현한 함수 사용
from layer import Sigmoid, Affine, MatMul
from net import TwoLayerNet

### Layer `Sigmoid`

In [2]:
sigmoid_layer = Sigmoid()
sigmoid_layer.forward(0)

0.5

### Layer `Affine`

In [3]:
W = np.random.randn(2, 4)
b = np.random.randn(1, 4)

affine_layer = Affine(W, b)

In [4]:
x = np.array([10, 20])

In [5]:
affine_layer.forward(x)

array([[  4.08292604, -40.14351268, -18.62407105,  45.02793981]])

### Net `TwoLayerNet`

In [6]:
input_size = 2
hidden_size = 4
output_size = 3

model = TwoLayerNet(input_size, hidden_size, output_size)
model

In [7]:
model.params

[array([[-0.13645805,  0.47204532, -0.45751287, -0.644823  ],
        [ 1.51522794, -0.60624208,  0.62303314,  0.28976967]]),
 array([1.22689355, 0.05798292, 2.32401729, 0.22278843]),
 array([[ 0.39187759,  1.21202468,  0.72130152],
        [-0.71981605,  0.18432567, -0.38570201],
        [ 0.96058287,  0.2408447 , -0.32947335],
        [ 0.38525547, -0.64227387, -0.56292897]]),
 array([-0.27685447,  0.48677322,  0.09687252])]

In [8]:
model.predict(x)

array([1.2269416 , 1.68662287, 0.26660559])

### Layer `MatMul`

In [10]:
matmul_layer = MatMul(W)
matmul_layer

In [11]:
matmul_layer.forward(x)

array([  4.78018077, -41.51383429, -18.81713205,  43.50384491])

In [15]:
dout = np.random.randn(2, 4)

matmul_layer.backward(dout)

array([[-0.65697643,  0.7189847 ],
       [-3.61760711, -0.83623554]])